name: markdown_editor_live
description: "A simple WYSIWYG markdown editor widget for Flutter"
version: 0.6.0
repository: https://github.com/janek-w/markdown_editor_live

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: